### ISSUE TITLE
inheritable relationships

### ISSUE THREAD

**Issue by amanique** [jasminb/jsonapi-converter#48]
"Have in mind that relationship (same as id) is inheritable and can be defined in a base class."

Hello, can you help me do this, please?

```
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "type",
        visible = true,
        defaultImpl = Vehicle.class
)

@JsonSubTypes({
        @JsonSubTypes.Type(value = Car.class, name = "CAR"),
        @JsonSubTypes.Type(value = Bike.class, name = "BIKE")
})


@Type("vehicle")
public class Vehicle {
    
    @Id
    public String id;

    @Relationship("address")
    protected Address address;

}

@Type("vehicle")
public class Car extends Vehicle {
    
    @Id
    public String id;

    @Relationship("address")
    protected Address address;

}

```

If i remove @Id or @Relationship from the children, they are not inherited from the parent and returns an error "All resource classes must have a field annotated with the @Id annotation" or, in the case of the Relationships, just returns null.
Even if when change @Type to car.

Thank you

**Comment by amanique** [comment]
Nevermind. I realised it is solved on 0.3;
The only thing missing now is Retrofit 2 ;)

**Comment by jasminb** [comment]
Hey @amanique, you can use snapshot version of the lib (0.4) which brings retrofit 2.0 support.

**Comment by amanique** [comment]
Thank you, i tried but the snapshot didn't have retrofit 2 aswell.

**Comment by jasminb** [comment]
Hey, yeah I did not push the latest version to sonatype repos. I built it few minutes ago and pushed it (not sure how long it takes for it to propagate tho).

**Comment by amanique** [comment]
OK. thank you very much. One last question :D : I'm doing the serialization with relationships and it's all good, I'm just not being able to include the related objects. Can you help please?

**Comment by jasminb** [comment]
Hey,
You are the second one asking about full relationship serialisation; initially when I started this project, I intended it to be used on client side, clients do not require full serialisation of relationships since by spec relationships cannot be implicitly created on POST/PUT but rather can be created against already existing resources.

Since it appears folks do have use for full serialisation, I will extend annotations to allow for specifying wether relationship should be fully serialised or it should be only serialised as type/id combination.

**Comment by amanique** [comment]
Great, thank you man, amazing work.

**Comment by ericn37** [comment]
I've tried this with Retrofit 2 but all I got is the **Vehicle** class, not the **Car** class
