### ISSUE TITLE
JSONAPIConverterFactory cannot support Retrofit to have multiple converters

### ISSUE THREAD

**Issue by fabricehong** [jasminb/jsonapi-converter#8]
Hi,

As defined by Retrofit Converters, if a factory cannot handle the given type, fromResponseBody and toRequestBody it should return null so other factories can be tried : https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Converter.java

Since some of the responses I need to parse doesn't follow jsonapi, my only way to cope with that is to have a second retrofit object in my dependency injection graph.

**Comment by jasminb** [comment]
Hey,

So, you would expect that check is made if passed type is registered with JSON API converter, and if not, to return `null` instead?

**Comment by jasminb** [comment]
I've pushed code changes that correctly handle `unknown` types.

In case unknown type is encountered, factory will return `null` instead of returning JSON API converter that will produce exception if used.

I've also added convenience method that allows registering `alternative` factory to be used in case JSON API converter factory is unable to handle incoming conversion request.

**Comment by fabricehong** [comment]
great, now works well and I'm able to provide multiple converters to Retrofit.

thx !

**Comment by iadcialim** [comment]
@fabricehong Sorry, is it possible for you show an example here on show to have a separate converter for the RequestBody and ResponseBody?
