### ISSUE TITLE
Errors member of the JSONAPIDocument is missing

### ISSUE THREAD

**Issue by nikolafon** [jasminb/jsonapi-converter#83]
Spec says:
"A document MUST contain at least one of the following top-level members:

data: the document’s “primary data”
errors: an array of error objects
meta: a meta object that contains non-standard meta-information."

As a developer I want to be able to serialize `JSONAPDocument` to JSON with only errors member set, currently this member is missing.

**Comment by jasminb** [comment]
Issue was fixed and pushed to `develop`.  Latest snapshot release can be used to test it.

In order to create `error` response factory method was added to the `JSONAPIDocument`:

```java
public static JSONAPIDocument<?> createErrorDocument(Iterable<? extends Error> errors) {}
```

One can either use provided `Error` class to construct errors (this class holds attributes recommended by the specification, or extend the `Error` class to roll customised error structure.

Since by specification, there is no concept of one but at least one error, document is constructed using `Iterable`.

Example:

```java
Error error = new Error();
error.setCode("code");
		
JSONAPIDocument<?> document = JSONAPIDocument.createErrorDocument(Collections.singleton(error));

converter.writeDocument(document);
```

This will produce:

```json
{
  "errors": [
    {
      "code": "code"
    }
  ]
}
```
